apiVersion: apps/v1
kind: Deployment
metadata:
  name: IMAGE_PLACEHOLDER
  labels:
    app: IMAGE_PLACEHOLDER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: IMAGE_PLACEHOLDER
  template:
    metadata:
      labels:
        app: IMAGE_PLACEHOLDER
    spec:
      containers:
      - name: IMAGE_PLACEHOLDER
        image: IMAGE_PLACEHOLDER:latest
        ports:
        - containerPort: 80
